const UUID_LIKE_THREAD_NAME_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const SHORT_HEX_THREAD_NAME_REGEX = /^[a-f0-9]{4,8}$/i;

import i18n from "@/locales/i18n";

export function looksAutoGeneratedThreadName(name: string) {
  const trimmed = name.trim();
  return (
    trimmed === i18n.t("newAgent", { ns: "threads" }) ||
    trimmed.startsWith("Agent ") ||
    SHORT_HEX_THREAD_NAME_REGEX.test(trimmed) ||
    UUID_LIKE_THREAD_NAME_REGEX.test(trimmed)
  );
}

export function clampThreadName(name: string, maxLength = 38): string | null {
  const trimmed = name.replace(/\s+/g, " ").trim();
  if (!trimmed) {
    return null;
  }
  return trimmed.length > maxLength
    ? `${trimmed.slice(0, maxLength)}…`
    : trimmed;
}
